# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HidYGdcKZOUdPSbyBHirV9O60VSA7urN
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
import matplotlib.pyplot as plt
# %matplotlib inline
bos1=pd.read_csv("BostonHousing.csv")
bos1.head()

x=bos1.iloc[:,0:13]
y=bos1["medv"]
y.head()

correlations=bos1.corr()
correlations

import seaborn as sns
names=[]
correlations=bos1.corr()
sns.heatmap(correlations,square=True,cmap="YlGnBu")
plt.yticks(rotation=0)
plt.xticks(rotation=90)
plt.show()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)
print(x_train.shape)
print(x_test.shape)

lm=LinearRegression()
model=lm.fit(x_train,y_train)

pred_y=model.predict(x_test)

print("error: %.2f" % mean_squared_error(y_test,pred_y))
print("accuracy : %.2f" %r2_score(y_test,pred_y))

